#!/usr/bin/with-contenv bash

# make folder
mkdir -p \
	/config/mongodb

[[ ! -e /config/.env ]] && \
	cp /app/voicybot/.env.sample /config/.env

cp -f /config/.env /app/voicybot/.env

# permissions
chown -R abc:abc \
	/config \
	/app/voicybot
